"""
Slidev Exporter Service
Creates Slidev markdown presentations from architecture diagrams
Slidev: https://sli.dev/
"""

import logging
from typing import List
from datetime import datetime

from app.models.schemas import Node, Edge

logger = logging.getLogger(__name__)


class SlidevExporter:
    """Service for exporting architecture diagrams to Slidev markdown"""

    def __init__(self):
        pass

    def create_slidev(
        self,
        nodes: List[Node],
        edges: List[Edge],
        mermaid_code: str,
        title: str = "Architecture Diagram",
    ) -> str:
        """Create a Slidev markdown presentation"""

        try:
            slides = []

            # Frontmatter and title slide
            slides.append(self._create_frontmatter(title))

            # Slide 1: Overview
            slides.append(self._create_overview_slide(nodes, edges))

            # Slide 2: Mermaid diagram
            slides.append(self._create_diagram_slide(mermaid_code))

            # Slide 3: Components breakdown
            slides.append(self._create_components_slide(nodes))

            # Slide 4: Connections breakdown
            slides.append(self._create_connections_slide(nodes, edges))

            # Slide 5: Summary
            slides.append(self._create_summary_slide(nodes, edges))

            markdown_content = "\n\n---\n\n".join(slides)

            logger.info(f"Created Slidev presentation with {len(slides)} slides")
            return markdown_content

        except Exception as e:
            logger.error(f"Failed to create Slidev presentation: {e}", exc_info=True)
            raise

    def _create_frontmatter(self, title: str) -> str:
        """Create Slidev frontmatter configuration"""

        return f"""---
theme: default
background: https://source.unsplash.com/collection/94734566/1920x1080
class: text-center
highlighter: shiki
lineNumbers: false
info: |
  ## {title}

  Generated by SmartArchitect AI
  {datetime.now().strftime('%Y-%m-%d')}
drawings:
  persist: false
transition: slide-left
title: {title}
mdc: true
---

# {title}

AI-Powered Architecture Design

<div class="pt-12">
  <span @click="$slidev.nav.next" class="px-2 py-1 rounded cursor-pointer" hover="bg-white bg-opacity-10">
    Press Space for next page <carbon:arrow-right class="inline"/>
  </span>
</div>

<div class="abs-br m-6 flex gap-2">
  <button @click="$slidev.nav.openInEditor()" title="Open in Editor" class="text-xl slidev-icon-btn opacity-50 !border-none !hover:text-white">
    <carbon:edit />
  </button>
  <a href="https://github.com/yourusername/smartarchitect" target="_blank" alt="GitHub" title="Open in GitHub"
    class="text-xl slidev-icon-btn opacity-50 !border-none !hover:text-white">
    <carbon-logo-github />
  </a>
</div>"""

    def _create_overview_slide(self, nodes: List[Node], edges: List[Edge]) -> str:
        """Create overview slide"""

        # Group components by type
        types_count = {}
        for node in nodes:
            node_type = node.type or "default"
            types_count[node_type] = types_count.get(node_type, 0) + 1

        types_list = "\n".join([f"- **{t.upper()}**: {count}" for t, count in types_count.items()])

        return f"""# System Overview

## Architecture Statistics

<div class="grid grid-cols-2 gap-4">
<div>

### Components
{len(nodes)} total components

{types_list}

</div>
<div>

### Connections
{len(edges)} total connections

Highly connected system with clear separation of concerns

</div>
</div>

<style>
h2 {{
  background-color: #2B90B6;
  background-image: linear-gradient(45deg, #4EC5D4 10%, #146b8c 20%);
  background-size: 100%;
  -webkit-background-clip: text;
  -moz-background-clip: text;
  -webkit-text-fill-color: transparent;
  -moz-text-fill-color: transparent;
}}
</style>"""

    def _create_diagram_slide(self, mermaid_code: str) -> str:
        """Create slide with Mermaid diagram"""

        return f"""# Architecture Diagram

```mermaid {{scale: 0.7}}
{mermaid_code}
```

<style>
.slidev-layout {{
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}}
</style>"""

    def _create_components_slide(self, nodes: List[Node]) -> str:
        """Create components breakdown slide"""

        # Group by type
        types = {}
        for node in nodes:
            node_type = node.type or "default"
            if node_type not in types:
                types[node_type] = []
            types[node_type].append(node.data.label)

        components_markdown = "\n\n".join([
            f"### {node_type.upper()}\n\n" + "\n".join([f"- {label}" for label in labels])
            for node_type, labels in types.items()
        ])

        return f"""# System Components

<div class="grid grid-cols-2 gap-4">

<div>

{components_markdown.split('### ')[1] if '### ' in components_markdown else components_markdown}

</div>

<div>

{'### ' + '### '.join(components_markdown.split('### ')[2:]) if components_markdown.count('### ') > 1 else ''}

</div>

</div>

<arrow v-click="3" x1="400" y1="420" x2="230" y2="330" color="#564" width="3" arrowSize="1" />"""

    def _create_connections_slide(self, nodes: List[Node], edges: List[Edge]) -> str:
        """Create connections breakdown slide"""

        connections_list = []
        for edge in edges:
            source_node = next((n for n in nodes if n.id == edge.source), None)
            target_node = next((n for n in nodes if n.id == edge.target), None)

            if source_node and target_node:
                label_text = f" `{edge.label}`" if edge.label else ""
                connections_list.append(
                    f"- **{source_node.data.label}** → **{target_node.data.label}**{label_text}"
                )

        connections_markdown = "\n".join(connections_list)

        return f"""# Component Connections

## Data Flow & Communication

<div v-click>

{connections_markdown}

</div>

<div v-after class="abs-br m-6 text-sm opacity-50">
  Total: {len(edges)} connections
</div>"""

    def _create_summary_slide(self, nodes: List[Node], edges: List[Edge]) -> str:
        """Create summary slide"""

        return f"""# Summary

<div class="grid grid-cols-2 gap-4">
<div>

## Key Highlights

- ✅ **{len(nodes)} Components** - Modular design
- ✅ **{len(edges)} Connections** - Clear data flow
- ✅ **Scalable** - Easy to extend
- ✅ **Maintainable** - Well-structured

</div>
<div>

## Next Steps

1. 📋 Review architecture decisions
2. 🔍 Identify optimization opportunities
3. 🚀 Begin implementation
4. 📊 Monitor and iterate

</div>
</div>

<div class="abs-br m-6">
  <span class="text-sm opacity-50">Generated by SmartArchitect AI • {datetime.now().strftime('%Y')}</span>
</div>

<style>
h1 {{
  background-color: #2B90B6;
  background-image: linear-gradient(45deg, #4EC5D4 10%, #146b8c 20%);
  background-size: 100%;
  -webkit-background-clip: text;
  -moz-background-clip: text;
  -webkit-text-fill-color: transparent;
  -moz-text-fill-color: transparent;
}}
</style>"""


# Helper function to create exporter instance
def create_slidev_exporter() -> SlidevExporter:
    """Create a SlidevExporter instance"""
    return SlidevExporter()
