import { Theme } from "./types";

/**
 * Theme Presets
 * Collection of pre-defined themes for architecture diagrams
 */

const defaultFonts = {
  family: "Inter, system-ui, sans-serif",
  size: {
    node: "14px",
    label: "12px",
    edge: "11px",
  },
  weight: {
    normal: 400,
    bold: 600,
  },
};

export const THEME_PRESETS: Theme[] = [
  {
    id: "smartarchitect-default",
    name: "SmartArchitect Default",
    description: "Clean and modern default theme",
    category: "professional",
    colors: {
      apiNode: {
        border: "#3b82f6",
        background: "#eff6ff",
        text: "#1e40af",
        icon: "#3b82f6",
        shadow: "rgba(59, 130, 246, 0.1)",
      },
      serviceNode: {
        border: "#a855f7",
        background: "#faf5ff",
        text: "#7e22ce",
        icon: "#a855f7",
        shadow: "rgba(168, 85, 247, 0.1)",
      },
      databaseNode: {
        border: "#10b981",
        background: "#ecfdf5",
        text: "#047857",
        icon: "#10b981",
        shadow: "rgba(16, 185, 129, 0.1)",
      },
      gatewayNode: {
        border: "#f59e0b",
        background: "#fffbeb",
        text: "#b45309",
        icon: "#f59e0b",
        shadow: "rgba(245, 158, 11, 0.1)",
      },
      defaultNode: {
        border: "#6b7280",
        background: "#f9fafb",
        text: "#374151",
        icon: "#6b7280",
        shadow: "rgba(107, 114, 128, 0.1)",
      },
      cacheNode: {
        border: "#eab308",
        background: "#fefce8",
        text: "#854d0e",
        icon: "#eab308",
        shadow: "rgba(234, 179, 8, 0.1)",
      },
      queueNode: {
        border: "#6366f1",
        background: "#eef2ff",
        text: "#3730a3",
        icon: "#6366f1",
        shadow: "rgba(99, 102, 241, 0.1)",
      },
      storageNode: {
        border: "#64748b",
        background: "#f8fafc",
        text: "#1e293b",
        icon: "#64748b",
        shadow: "rgba(100, 116, 139, 0.1)",
      },
      clientNode: {
        border: "#06b6d4",
        background: "#ecfeff",
        text: "#155e75",
        icon: "#06b6d4",
        shadow: "rgba(6, 182, 212, 0.1)",
      },
      edges: {
        stroke: "#9ca3af",
        strokeWidth: 2,
        animated: false,
      },
      canvas: {
        background: "#ffffff",
        grid: "#e5e7eb",
        gridSize: 20,
      },
      accent: "#8b5cf6",
      muted: "#d1d5db",
    },
    fonts: defaultFonts,
  },
  {
    id: "corporate-professional",
    name: "大厂述职风格",
    description: "Professional corporate presentation style",
    category: "professional",
    colors: {
      apiNode: {
        border: "#2563eb",
        background: "#dbeafe",
        text: "#1e3a8a",
        icon: "#2563eb",
        shadow: "rgba(37, 99, 235, 0.15)",
      },
      serviceNode: {
        border: "#4f46e5",
        background: "#e0e7ff",
        text: "#3730a3",
        icon: "#4f46e5",
        shadow: "rgba(79, 70, 229, 0.15)",
      },
      databaseNode: {
        border: "#059669",
        background: "#d1fae5",
        text: "#065f46",
        icon: "#059669",
        shadow: "rgba(5, 150, 105, 0.15)",
      },
      gatewayNode: {
        border: "#dc2626",
        background: "#fee2e2",
        text: "#991b1b",
        icon: "#dc2626",
        shadow: "rgba(220, 38, 38, 0.15)",
      },
      defaultNode: {
        border: "#475569",
        background: "#f1f5f9",
        text: "#1e293b",
        icon: "#475569",
        shadow: "rgba(71, 85, 105, 0.15)",
      },
      cacheNode: {
        border: "#f59e0b",
        background: "#fef3c7",
        text: "#92400e",
        icon: "#f59e0b",
        shadow: "rgba(245, 158, 11, 0.15)",
      },
      queueNode: {
        border: "#7c3aed",
        background: "#ede9fe",
        text: "#5b21b6",
        icon: "#7c3aed",
        shadow: "rgba(124, 58, 237, 0.15)",
      },
      storageNode: {
        border: "#64748b",
        background: "#e2e8f0",
        text: "#0f172a",
        icon: "#64748b",
        shadow: "rgba(100, 116, 139, 0.15)",
      },
      clientNode: {
        border: "#0891b2",
        background: "#cffafe",
        text: "#164e63",
        icon: "#0891b2",
        shadow: "rgba(8, 145, 178, 0.15)",
      },
      edges: {
        stroke: "#64748b",
        strokeWidth: 2.5,
        animated: false,
      },
      canvas: {
        background: "#f8fafc",
        grid: "#cbd5e1",
        gridSize: 25,
      },
      accent: "#4f46e5",
      muted: "#94a3b8",
    },
    fonts: {
      ...defaultFonts,
      weight: { normal: 500, bold: 700 },
    },
  },
  {
    id: "tech-minimal",
    name: "科技极简",
    description: "Minimalist tech-focused design",
    category: "minimal",
    colors: {
      apiNode: {
        border: "#06b6d4",
        background: "#ecfeff",
        text: "#0e7490",
        icon: "#06b6d4",
      },
      serviceNode: {
        border: "#8b5cf6",
        background: "#f5f3ff",
        text: "#6d28d9",
        icon: "#8b5cf6",
      },
      databaseNode: {
        border: "#14b8a6",
        background: "#f0fdfa",
        text: "#0f766e",
        icon: "#14b8a6",
      },
      gatewayNode: {
        border: "#f97316",
        background: "#fff7ed",
        text: "#c2410c",
        icon: "#f97316",
      },
      defaultNode: {
        border: "#52525b",
        background: "#fafafa",
        text: "#27272a",
        icon: "#52525b",
      },
      cacheNode: {
        border: "#facc15",
        background: "#fefce8",
        text: "#713f12",
        icon: "#facc15",
      },
      queueNode: {
        border: "#a855f7",
        background: "#faf5ff",
        text: "#6b21a8",
        icon: "#a855f7",
      },
      storageNode: {
        border: "#71717a",
        background: "#f4f4f5",
        text: "#18181b",
        icon: "#71717a",
      },
      clientNode: {
        border: "#22d3ee",
        background: "#ecfeff",
        text: "#155e75",
        icon: "#22d3ee",
      },
      edges: {
        stroke: "#a1a1aa",
        strokeWidth: 1.5,
        animated: false,
        strokeDasharray: "5,5",
      },
      canvas: {
        background: "#fafafa",
        grid: "#e4e4e7",
        gridSize: 15,
      },
      accent: "#06b6d4",
      muted: "#d4d4d8",
    },
    fonts: {
      family: "JetBrains Mono, monospace",
      size: { node: "13px", label: "11px", edge: "10px" },
      weight: { normal: 400, bold: 600 },
    },
  },
  {
    id: "hand-drawn",
    name: "手绘风格",
    description: "Sketch-like hand-drawn appearance",
    category: "sketch",
    colors: {
      apiNode: {
        border: "#2563eb",
        background: "#eff6ff",
        text: "#1e40af",
        icon: "#3b82f6",
      },
      serviceNode: {
        border: "#9333ea",
        background: "#faf5ff",
        text: "#6b21a8",
        icon: "#a855f7",
      },
      databaseNode: {
        border: "#059669",
        background: "#ecfdf5",
        text: "#047857",
        icon: "#10b981",
      },
      gatewayNode: {
        border: "#ea580c",
        background: "#fff7ed",
        text: "#c2410c",
        icon: "#f97316",
      },
      defaultNode: {
        border: "#525252",
        background: "#fafafa",
        text: "#262626",
        icon: "#737373",
      },
      cacheNode: {
        border: "#f59e0b",
        background: "#fffbeb",
        text: "#78350f",
        icon: "#fbbf24",
      },
      queueNode: {
        border: "#7c3aed",
        background: "#f5f3ff",
        text: "#5b21b6",
        icon: "#8b5cf6",
      },
      storageNode: {
        border: "#6b7280",
        background: "#f9fafb",
        text: "#1f2937",
        icon: "#9ca3af",
      },
      clientNode: {
        border: "#0891b2",
        background: "#cffafe",
        text: "#155e75",
        icon: "#06b6d4",
      },
      edges: {
        stroke: "#737373",
        strokeWidth: 2,
        animated: false,
        strokeDasharray: "8,4",
      },
      canvas: {
        background: "#fffef7",
        grid: "#e7e5e4",
        gridSize: 20,
      },
      accent: "#2563eb",
      muted: "#d6d3d1",
    },
    fonts: {
      family: "Comic Sans MS, cursive",
      size: { node: "14px", label: "12px", edge: "11px" },
      weight: { normal: 400, bold: 700 },
    },
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    description: "Futuristic neon-inspired theme",
    category: "vibrant",
    colors: {
      apiNode: {
        border: "#06b6d4",
        background: "#083344",
        text: "#67e8f9",
        icon: "#22d3ee",
        shadow: "0 0 20px rgba(6, 182, 212, 0.5)",
      },
      serviceNode: {
        border: "#c026d3",
        background: "#4a044e",
        text: "#f0abfc",
        icon: "#d946ef",
        shadow: "0 0 20px rgba(192, 38, 211, 0.5)",
      },
      databaseNode: {
        border: "#84cc16",
        background: "#1a2e05",
        text: "#bef264",
        icon: "#a3e635",
        shadow: "0 0 20px rgba(132, 204, 22, 0.5)",
      },
      gatewayNode: {
        border: "#f59e0b",
        background: "#451a03",
        text: "#fcd34d",
        icon: "#fbbf24",
        shadow: "0 0 20px rgba(245, 158, 11, 0.5)",
      },
      defaultNode: {
        border: "#6366f1",
        background: "#1e1b4b",
        text: "#a5b4fc",
        icon: "#818cf8",
        shadow: "0 0 20px rgba(99, 102, 241, 0.5)",
      },
      cacheNode: {
        border: "#facc15",
        background: "#422006",
        text: "#fde047",
        icon: "#fde047",
        shadow: "0 0 20px rgba(250, 204, 21, 0.5)",
      },
      queueNode: {
        border: "#a855f7",
        background: "#3b0764",
        text: "#e9d5ff",
        icon: "#c084fc",
        shadow: "0 0 20px rgba(168, 85, 247, 0.5)",
      },
      storageNode: {
        border: "#64748b",
        background: "#1e293b",
        text: "#cbd5e1",
        icon: "#94a3b8",
        shadow: "0 0 20px rgba(100, 116, 139, 0.5)",
      },
      clientNode: {
        border: "#14b8a6",
        background: "#042f2e",
        text: "#5eead4",
        icon: "#2dd4bf",
        shadow: "0 0 20px rgba(20, 184, 166, 0.5)",
      },
      edges: {
        stroke: "#22d3ee",
        strokeWidth: 2,
        animated: true,
      },
      canvas: {
        background: "#0f172a",
        grid: "#1e293b",
        gridSize: 20,
      },
      accent: "#06b6d4",
      muted: "#334155",
    },
    fonts: {
      family: "Orbitron, sans-serif",
      size: { node: "13px", label: "11px", edge: "10px" },
      weight: { normal: 500, bold: 700 },
    },
  },
  {
    id: "pastel",
    name: "Pastel Dreams",
    description: "Soft and gentle pastel colors",
    category: "vibrant",
    colors: {
      apiNode: {
        border: "#93c5fd",
        background: "#dbeafe",
        text: "#1e40af",
        icon: "#60a5fa",
      },
      serviceNode: {
        border: "#d8b4fe",
        background: "#f3e8ff",
        text: "#7e22ce",
        icon: "#c084fc",
      },
      databaseNode: {
        border: "#86efac",
        background: "#dcfce7",
        text: "#15803d",
        icon: "#4ade80",
      },
      gatewayNode: {
        border: "#fcd34d",
        background: "#fef3c7",
        text: "#a16207",
        icon: "#fbbf24",
      },
      defaultNode: {
        border: "#cbd5e1",
        background: "#f1f5f9",
        text: "#475569",
        icon: "#94a3b8",
      },
      cacheNode: {
        border: "#fde047",
        background: "#fef9c3",
        text: "#713f12",
        icon: "#facc15",
      },
      queueNode: {
        border: "#c4b5fd",
        background: "#ede9fe",
        text: "#6d28d9",
        icon: "#a78bfa",
      },
      storageNode: {
        border: "#e2e8f0",
        background: "#f8fafc",
        text: "#334155",
        icon: "#cbd5e1",
      },
      clientNode: {
        border: "#7dd3fc",
        background: "#e0f2fe",
        text: "#0c4a6e",
        icon: "#38bdf8",
      },
      edges: {
        stroke: "#cbd5e1",
        strokeWidth: 2,
        animated: false,
      },
      canvas: {
        background: "#fefce8",
        grid: "#fde68a",
        gridSize: 20,
      },
      accent: "#c084fc",
      muted: "#e2e8f0",
    },
    fonts: defaultFonts,
  },
  {
    id: "high-contrast",
    name: "High Contrast",
    description: "Maximum visibility and accessibility",
    category: "professional",
    colors: {
      apiNode: {
        border: "#000000",
        background: "#ffffff",
        text: "#000000",
        icon: "#000000",
        shadow: "0 4px 6px rgba(0, 0, 0, 0.3)",
      },
      serviceNode: {
        border: "#000000",
        background: "#ffff00",
        text: "#000000",
        icon: "#000000",
        shadow: "0 4px 6px rgba(0, 0, 0, 0.3)",
      },
      databaseNode: {
        border: "#000000",
        background: "#00ff00",
        text: "#000000",
        icon: "#000000",
        shadow: "0 4px 6px rgba(0, 0, 0, 0.3)",
      },
      gatewayNode: {
        border: "#000000",
        background: "#ff0000",
        text: "#ffffff",
        icon: "#ffffff",
        shadow: "0 4px 6px rgba(0, 0, 0, 0.3)",
      },
      defaultNode: {
        border: "#000000",
        background: "#e5e5e5",
        text: "#000000",
        icon: "#000000",
        shadow: "0 4px 6px rgba(0, 0, 0, 0.3)",
      },
      cacheNode: {
        border: "#000000",
        background: "#ffff00",
        text: "#000000",
        icon: "#000000",
        shadow: "0 4px 6px rgba(0, 0, 0, 0.3)",
      },
      queueNode: {
        border: "#000000",
        background: "#00ffff",
        text: "#000000",
        icon: "#000000",
        shadow: "0 4px 6px rgba(0, 0, 0, 0.3)",
      },
      storageNode: {
        border: "#000000",
        background: "#cccccc",
        text: "#000000",
        icon: "#000000",
        shadow: "0 4px 6px rgba(0, 0, 0, 0.3)",
      },
      clientNode: {
        border: "#000000",
        background: "#00ccff",
        text: "#000000",
        icon: "#000000",
        shadow: "0 4px 6px rgba(0, 0, 0, 0.3)",
      },
      edges: {
        stroke: "#000000",
        strokeWidth: 3,
        animated: false,
      },
      canvas: {
        background: "#ffffff",
        grid: "#cccccc",
        gridSize: 20,
      },
      accent: "#000000",
      muted: "#666666",
    },
    fonts: {
      ...defaultFonts,
      weight: { normal: 600, bold: 800 },
    },
  },
  {
    id: "monochrome",
    name: "Monochrome",
    description: "Elegant black and white theme",
    category: "minimal",
    colors: {
      apiNode: {
        border: "#1f2937",
        background: "#f9fafb",
        text: "#111827",
        icon: "#374151",
      },
      serviceNode: {
        border: "#374151",
        background: "#f3f4f6",
        text: "#1f2937",
        icon: "#4b5563",
      },
      databaseNode: {
        border: "#4b5563",
        background: "#e5e7eb",
        text: "#1f2937",
        icon: "#6b7280",
      },
      gatewayNode: {
        border: "#111827",
        background: "#d1d5db",
        text: "#000000",
        icon: "#374151",
      },
      defaultNode: {
        border: "#6b7280",
        background: "#ffffff",
        text: "#374151",
        icon: "#9ca3af",
      },
      cacheNode: {
        border: "#52525b",
        background: "#f4f4f5",
        text: "#27272a",
        icon: "#71717a",
      },
      queueNode: {
        border: "#3f3f46",
        background: "#fafafa",
        text: "#18181b",
        icon: "#52525b",
      },
      storageNode: {
        border: "#71717a",
        background: "#f9fafb",
        text: "#3f3f46",
        icon: "#a1a1aa",
      },
      clientNode: {
        border: "#52525b",
        background: "#fafafa",
        text: "#27272a",
        icon: "#71717a",
      },
      edges: {
        stroke: "#6b7280",
        strokeWidth: 2,
        animated: false,
      },
      canvas: {
        background: "#ffffff",
        grid: "#e5e7eb",
        gridSize: 20,
      },
      accent: "#1f2937",
      muted: "#d1d5db",
    },
    fonts: {
      family: "Georgia, serif",
      size: { node: "14px", label: "12px", edge: "11px" },
      weight: { normal: 400, bold: 700 },
    },
  },
  {
    id: "ocean-blue",
    name: "Ocean Blue",
    description: "Calm oceanic color palette",
    category: "vibrant",
    colors: {
      apiNode: {
        border: "#0891b2",
        background: "#cffafe",
        text: "#164e63",
        icon: "#06b6d4",
      },
      serviceNode: {
        border: "#0284c7",
        background: "#e0f2fe",
        text: "#075985",
        icon: "#0ea5e9",
      },
      databaseNode: {
        border: "#0369a1",
        background: "#bae6fd",
        text: "#0c4a6e",
        icon: "#0284c7",
      },
      gatewayNode: {
        border: "#0e7490",
        background: "#a5f3fc",
        text: "#155e75",
        icon: "#22d3ee",
      },
      defaultNode: {
        border: "#475569",
        background: "#f1f5f9",
        text: "#1e293b",
        icon: "#64748b",
      },
      cacheNode: {
        border: "#14b8a6",
        background: "#ccfbf1",
        text: "#134e4a",
        icon: "#2dd4bf",
      },
      queueNode: {
        border: "#3b82f6",
        background: "#dbeafe",
        text: "#1e3a8a",
        icon: "#60a5fa",
      },
      storageNode: {
        border: "#64748b",
        background: "#e2e8f0",
        text: "#1e293b",
        icon: "#94a3b8",
      },
      clientNode: {
        border: "#06b6d4",
        background: "#cffafe",
        text: "#164e63",
        icon: "#22d3ee",
      },
      edges: {
        stroke: "#06b6d4",
        strokeWidth: 2,
        animated: false,
      },
      canvas: {
        background: "#f0fdfa",
        grid: "#99f6e4",
        gridSize: 20,
      },
      accent: "#0891b2",
      muted: "#cbd5e1",
    },
    fonts: defaultFonts,
  },
  {
    id: "forest-green",
    name: "Forest Green",
    description: "Natural forest-inspired theme",
    category: "vibrant",
    colors: {
      apiNode: {
        border: "#16a34a",
        background: "#dcfce7",
        text: "#14532d",
        icon: "#22c55e",
      },
      serviceNode: {
        border: "#15803d",
        background: "#bbf7d0",
        text: "#052e16",
        icon: "#4ade80",
      },
      databaseNode: {
        border: "#166534",
        background: "#86efac",
        text: "#14532d",
        icon: "#22c55e",
      },
      gatewayNode: {
        border: "#84cc16",
        background: "#ecfccb",
        text: "#365314",
        icon: "#a3e635",
      },
      defaultNode: {
        border: "#65a30d",
        background: "#f7fee7",
        text: "#3f6212",
        icon: "#84cc16",
      },
      cacheNode: {
        border: "#a3e635",
        background: "#ecfccb",
        text: "#3f6212",
        icon: "#bef264",
      },
      queueNode: {
        border: "#10b981",
        background: "#d1fae5",
        text: "#065f46",
        icon: "#34d399",
      },
      storageNode: {
        border: "#84cc16",
        background: "#f7fee7",
        text: "#365314",
        icon: "#a3e635",
      },
      clientNode: {
        border: "#14b8a6",
        background: "#ccfbf1",
        text: "#134e4a",
        icon: "#2dd4bf",
      },
      edges: {
        stroke: "#4ade80",
        strokeWidth: 2,
        animated: false,
      },
      canvas: {
        background: "#f0fdf4",
        grid: "#bbf7d0",
        gridSize: 20,
      },
      accent: "#16a34a",
      muted: "#d9f99d",
    },
    fonts: defaultFonts,
  },
  {
    id: "sunset-orange",
    name: "Sunset Orange",
    description: "Warm sunset-inspired colors",
    category: "vibrant",
    colors: {
      apiNode: {
        border: "#ea580c",
        background: "#ffedd5",
        text: "#7c2d12",
        icon: "#f97316",
      },
      serviceNode: {
        border: "#dc2626",
        background: "#fee2e2",
        text: "#7f1d1d",
        icon: "#ef4444",
      },
      databaseNode: {
        border: "#d97706",
        background: "#fef3c7",
        text: "#78350f",
        icon: "#f59e0b",
      },
      gatewayNode: {
        border: "#c2410c",
        background: "#fed7aa",
        text: "#7c2d12",
        icon: "#fb923c",
      },
      defaultNode: {
        border: "#f59e0b",
        background: "#fffbeb",
        text: "#78350f",
        icon: "#fbbf24",
      },
      cacheNode: {
        border: "#fbbf24",
        background: "#fef9c3",
        text: "#713f12",
        icon: "#fde047",
      },
      queueNode: {
        border: "#f43f5e",
        background: "#ffe4e6",
        text: "#881337",
        icon: "#fb7185",
      },
      storageNode: {
        border: "#92400e",
        background: "#fed7aa",
        text: "#451a03",
        icon: "#c2410c",
      },
      clientNode: {
        border: "#fb923c",
        background: "#ffedd5",
        text: "#7c2d12",
        icon: "#fdba74",
      },
      edges: {
        stroke: "#fb923c",
        strokeWidth: 2,
        animated: false,
      },
      canvas: {
        background: "#fffaf0",
        grid: "#fed7aa",
        gridSize: 20,
      },
      accent: "#ea580c",
      muted: "#fde68a",
    },
    fonts: defaultFonts,
  },
  {
    id: "midnight-purple",
    name: "Midnight Purple",
    description: "Deep purple night theme",
    category: "vibrant",
    colors: {
      apiNode: {
        border: "#7c3aed",
        background: "#ede9fe",
        text: "#4c1d95",
        icon: "#8b5cf6",
      },
      serviceNode: {
        border: "#9333ea",
        background: "#f3e8ff",
        text: "#581c87",
        icon: "#a855f7",
      },
      databaseNode: {
        border: "#a855f7",
        background: "#fae8ff",
        text: "#701a75",
        icon: "#c084fc",
      },
      gatewayNode: {
        border: "#6366f1",
        background: "#e0e7ff",
        text: "#3730a3",
        icon: "#818cf8",
      },
      defaultNode: {
        border: "#8b5cf6",
        background: "#f5f3ff",
        text: "#5b21b6",
        icon: "#a78bfa",
      },
      cacheNode: {
        border: "#d946ef",
        background: "#fae8ff",
        text: "#86198f",
        icon: "#e879f9",
      },
      queueNode: {
        border: "#6366f1",
        background: "#e0e7ff",
        text: "#3730a3",
        icon: "#818cf8",
      },
      storageNode: {
        border: "#7c3aed",
        background: "#ede9fe",
        text: "#5b21b6",
        icon: "#a78bfa",
      },
      clientNode: {
        border: "#c084fc",
        background: "#f3e8ff",
        text: "#6b21a8",
        icon: "#d8b4fe",
      },
      edges: {
        stroke: "#a78bfa",
        strokeWidth: 2,
        animated: false,
      },
      canvas: {
        background: "#faf5ff",
        grid: "#e9d5ff",
        gridSize: 20,
      },
      accent: "#7c3aed",
      muted: "#ddd6fe",
    },
    fonts: defaultFonts,
  },
];

export const DEFAULT_THEME_ID = "smartarchitect-default";

export function getThemeById(id: string): Theme | undefined {
  return THEME_PRESETS.find((theme) => theme.id === id);
}

export function getThemesByCategory(category: string): Theme[] {
  return THEME_PRESETS.filter((theme) => theme.category === category);
}
